---

organization: com.example
artifact: memento-finatra
version: "{{ memento_finatra_version }}"
extension: jar
main_class: com.example.memento.finatra.Main

# ports
port: 7771
admin_port: 9991
proxy_port: 7770
proxy_admin_port: 9990

# artifact
base_dir: "/opt/{{ artifact }}"
bin_dir: "{{ base_dir }}/bin"
artifact_file: "{{ bin_dir }}/{{ organization }}.{{ artifact }}-{{ version }}.{{ extension }}"

# config
service_name: "{{ artifact }}"
script_dir: "{{ base_dir }}/script"
start_script: "{{ script_dir }}/start"
conf_dir: "{{ base_dir }}/conf"
pid_file: "/var/run/{{ artifact }}.pid"
app_config: "{{ conf_dir }}/application.conf"
log_config: "{{ conf_dir }}/logback.xml"

# nginx
nginx_site_name: "{{ artifact }}"
nginx_base: "{{ base_dir }}/nginx"
nginx_www_dir: "{{ nginx_base }}/www"
nginx_admin_user: admin
nginx_admin_password: TODO
nginx_admin_htpasswd_file: "{{ nginx_base }}/pwd"

# elasticsearch
elasticsearch_cluster_name: memento
