---

- name: Install maven
  apt: pkg=maven state=present

- name: Create maven dir
  file: path={{ maven_dir }} state=directory

- name: Configure maven settings.xml
  template: src=settings.xml.j2 dest={{ maven_settings_xml }}
