---

- name: Create conf dir
  file: path={{ conf_dir }} state=directory

- name: Config application.conf
  template: src=conf/application.conf.j2 dest={{ app_config }}
  notify: restart service

- name: Config logback.xml
  template: src=conf/logback.xml.j2 dest={{ log_config }}
  notify: restart service
