---

- name: Get checksum for existing artifact
  stat: path={{ artifact_file }}
  register: existing_checksum

- name: Create ivy dir
  file: path={{ ivy_dir }} state=directory

- name: Install ivy
  apt: pkg=ivy state=present

- name: Configure ivysettings.xml
  template: src=ivy/ivysettings.xml.j2 dest={{ ivy_settings_xml }}

- name: Configure ivy.xml
  template: src=ivy/ivy.xml.j2 dest={{ ivy_xml }}

- name: Retrieve new version with ivy
  command: "java -jar /usr/share/java/ivy.jar -retrieve {{ bin_dir }}/{{ ivy_retrieve_pattern }} -settings {{ ivy_settings_xml }} -ivy {{ ivy_xml }} -sync"

- name: Get checksum for new artifact
  stat: path={{ artifact_file }}
  register: new_checksum

- name: Stop running service
  service: name={{ service_name }} state=stopped
  ignore_errors: yes
  when: existing_checksum.stat.md5 is not defined or existing_checksum.stat.md5 != new_checksum.stat.md5
